[package]
name = "scylla-rust-lesson"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = {version = "0.8", features = ["v4"]}
tokio = {version = "1.1", features = ["full"]}
scylla = "0.3"
chrono = "0.4"
